services:
  app:
    image: mcr.microsoft.com/devcontainers/dotnet:1-9.0-bookworm
    working_dir: /workspaces/xtools
    ports:
      - "5198:5198"
    volumes:
      - .:/workspaces/xtools
    command: dotnet watch run --urls http://0.0.0.0:5198
    user: vscode
